nodeLinker: node-modules

npmScopes:
  requinard:
    npmRegistryServer: "https://registry.requinard.nl/api/packages/requinard/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
